### ISSUE TITLE
为什么开那么多文件夹呢？

### ISSUE THREAD

**Issue by Rratic** [WarfarinBloodanger/ff0-script#3]
热知识：git可以用来比较版本间的区别

**Comment by WarfarinBloodanger** [comment]
谢谢提醒。主要是因为本人也不是 github 常客 /kk。

然后让用户一次性下载到前面所有版本的虚拟机，在某种意义上可以帮助本人调试。

比如以前 1.6 版本出了一个 bug，1.5 版本没有，就有人反映说“1.6 版本有 xxx 漏洞但是 1.5 没有”，于是我直接比较了两个版本的代码找出了 bug。

Release 的话下载以前版本的要一个一个去点。

**Comment by Rratic** [comment]
> Release 的话下载以前版本的要一个一个去点。

但是
> 我直接比较了两个版本的代码找出了 bug。

> git可以用来比较版本间的区别
